[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
assignment_0 = "BM6SxJ3W35MJRuiTZmTDh9r1CaExtafcVjYsp8Tvtj8v"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
